# Generated by Django 5.1.1 on 2024-10-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=70)),
                ('d_id', models.IntegerField()),
                ('d_email', models.EmailField(max_length=254)),
                ('d_hos', models.CharField(max_length=70)),
            ],
        ),
    ]
