# Generated by Django 5.1.1 on 2024-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='comment',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
